apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dqn-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dqn-scaler-role
subjects:
  - kind: ServiceAccount
    name: dqn-scaler
    namespace: default
